### ISSUE TITLE
rpm打包成功后，使用rpm -ivh安装，报错openresty >= 1.15.8.1 is needed by apisix-0.8-0.noarch

### ISSUE THREAD

**Issue by Miss-you** [api7/apisix-build-tools#1]
rpm打包成功后，使用rpm -ivh安装，报错openresty >= 1.15.8.1 is needed by apisix-0.8-0.noarch

查看openresty 版本，

openresty -v
nginx version: openresty/1.15.8.2

安装时去掉依赖检查，可以安装成功

rpm -ivh apisix-0.8-0.noarch.rpm --nodeps

**Comment by membphis** [comment]
Is your openresty compiled by yourself?

**Comment by Miss-you** [comment]
yes, it is.

**Comment by Miss-you** [comment]
这个项目不在apache中就不需要一直用中文吧。
tlinux1.2和tlinux2.2的标准镜像源中没有openresty，我只能手动编译并安装

**Comment by Miss-you** [comment]
安装命令如下：

```
wget https://openresty.org/download/openresty-1.15.8.2.tar.gz
 tar -zxvf openresty-1.15.8.2.tar.gz
cd openresty-1.15.8.2
./configure --with-pcre-jit --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_v2_module

make -j2
make install
export PATH=/usr/local/openresty/bin:$PATH
```

**Comment by imjoey** [comment]
@Miss-you Hi, in this case, you could try using `--nodeps` to disable dependencies checking at installing.

**Comment by imjoey** [comment]
It's been a long time since the last activity. I would close this issue. Please feel free to reopen this if needed.
