### ISSUE TITLE
discuss: does the packaging method should be updated?

### ISSUE THREAD

**Issue by idbeta** [api7/apisix-build-tools#11]
I have learned some well-known open-source projects and found that their packaging methods have similarities. I wonder if the packaging methods of apisix should learned from them?

|   | tyk | kong | traefik  | skywalking | envoy | tidb |
| ------------- | ------------- |  ------------- |------------- | ------------- |  ------------- | ------------- |
| Project language  | golang  | lua  | golang  | java  | c++  | golang  |
| Packaging env | dockerfile  | dockerfile  | dockerfile  |  | docker  |  |
| Packaging method  | shell  | makefile  | makefile  | mvnw  | shell  | makefile  |

In these projects, the technology stacks of Kong and apisix are the same, and I think in these projects, Kong’s method is better: deploy the packaging environment via docker, so that the environment is clean and unified every time; packaging via `makefile` , so that the packaging entry is the same, passing different parameters can make different packages.
What do you think?

**Comment by membphis** [comment]
`makefile + dockerfile` is a better way. nice +1

**Comment by idbeta** [comment]
Now, the packaging method of APISIX is to use shell scripts to execute, which greatly depends on the environment of the packaging machine. Moreover, different packages need to execute different shell scripts. I think it needs to be improved. My suggestions are as follows:
1. Use makefile to achieve a unified packaging entry
2. There is no dependency on the packaged host environment, and the packaged environment needs to be deployed by docker
3. Support rpm, deb and other types of packages according to makefile parameters
4. Support APISIX and dashboard packages according to the parameters of makefile
I will submit a PR to achieve these points.

**Comment by imjoey** [comment]
@membphis probably this has been done via Makefile + Dockerfile, so I would close this issue. Feel free to reopen if anything unexpected.
