### ISSUE TITLE
what's the difference between "APISIX" and "APISIX OpenResty" 

### ISSUE THREAD

**Issue by kerneltravel** [api7/apisix-build-tools#151]
according to doc of apisix plugin real-ip (https://apisix.apache.org/zh/docs/apisix/plugins/real-ip/ ), which "requires APISIX to run on APISIX-OpenResty." 
and refer to another doc https://apisix.apache.org/docs/apisix/how-to-build/#step-6-build-openresty-for-apache-apisix .
so  APISIX is NOT equal to APISIX OpenResty ? 

and how to judge whether or not that my installed apisix has include "APISIX OpenResty" feature ,e.g real-ip . 

sorry for this somewhat newbie-like question.

**Comment by juzhiyuan** [comment]
> so APISIX is NOT equal to APISIX OpenResty ?

AFAIK, apisix contains a package called apisix-base, and apisix-base is equal to the openresty. cc @tzssangglass to have a check

**Comment by kerneltravel** [comment]
ok , after check my rpm-installed APISIX package, I'v found that APISIX and APISIX-base ( the APISIX OpenResty) has been installed.
`$ rpm -qa | grep -i apisix
apache-apisix-repo-1.0-1.noarch
apisix-base-1.19.9.1.0-0.el7.x86_64
apisix-dashboard-2.10.1-0.el7.x86_64
apisix-2.11.0-0.el7.x86_64`

tkx, @juzhiyuan

**Comment by tzssangglass** [comment]
now APISIX OpenResty is named as `apisix-base`, you can use `yum info apisix-base` to know what ti is.
