### ISSUE TITLE
proposal: new packaging method

### ISSUE THREAD

**Issue by idbeta** [api7/apisix-build-tools#16]
### Background
Some time ago I researched some well-known open source [projects,](https://github.com/api7/build-tools/issues/11) compared their packaging methods, and found that the packaging method of Apache APISIX method has many problems.
1. The packaging method of Apache APISIX is to use shell scripts to execute, which greatly depends on the environment of the packaging machine. If you want to maintain the same packaging environment every time, we should use docker to deploy.
2. Deb package or other type packages are not supported, 
3. APISIX and APISIX dashboard packaging scripts are different, there is no unified entry. 

I think they need to be improved. 

### How
1. Use makefile to achieve a unified packaging entry
2. There is no dependency on the packaged host environment, and the packaged environment needs to be deployed by dockerfile
3. Support rpm, deb and other types of packages according to makefile parameters
4. Support APISIX and dashboard packages according to the parameters of makefile

<img src="https://user-images.githubusercontent.com/7396835/105331800-d3582980-5c0e-11eb-8b09-28a470ebccfa.png" width="50%" height="50%">

### References
https://github.com/Kong/kong-build-tools
https://github.com/apache/apisix-docker/blob/master/all-in-one/apisix-dashboard/Dockerfile

**Comment by membphis** [comment]
We need a flowchart to show how to implement it.

Two important steps:

1. Build the target file (apisix lua files + so files)
2. Packaging (for example: rpm, deb package)

**Comment by idbeta** [comment]
> We need a flowchart to show how to implement it.
> 
> Two important steps:
> 
> 1. Build the target file (apisix lua files + so files)
> 2. Packaging (for example: rpm, deb package)

According to your and @moonming 's suggestions, I revised the proposal, and you can look at it again. The implementation plan will be quite different from the [current pr](https://github.com/api7/build-tools/pull/14).

**Comment by idbeta** [comment]
ping @moonming @membphis

**Comment by idbeta** [comment]
After PR #23 and #25, I think this issue can be closed now.
