### ISSUE TITLE
Not found changelog in rpm package

### ISSUE THREAD

**Issue by kwanhur** [api7/apisix-build-tools#164]
https://github.com/apache/apisix/discussions/6386#discussion-3889085

After installed apisix-2.12.0-0.el7.x86_64 with yum on CentOS7, I have a look at rpm -q --[changelog](https://github.com/apache/apisix/blob/master/CHANGELOG.md#2120) apisix the changelog, but it shows nothing :-(.

_Will the changelog adds to package?_

It doesn't specify --changelog at [packaging by fpm](https://github.com/api7/apisix-build-tools/blob/f307517225533776647fd2ea29ed4edc4a6bc620/package-apisix-base.sh#L22-L42).

fpm supports changelog flag for rpm dep but not apk:

--rpm-changelog
--dep-changelog
Refers from [fpm-cli](https://fpm.readthedocs.io/en/latest/cli-reference.html).

dependent package `openresty-*` can find it.
```bash
[vagrant@lvs ~]$ rpm -q --changelog openresty-openssl111-devel-1.1.1l-1.el7.x86_64
* Tue May 11 2021 Jiahao Wang 1.1.1k-1
- upgraded OpenSSL to 1.1.1k.

* Thu Dec 10 2020 Yichun Zhang (agentzh) 1.1.1i-1
- upgraded OpenSSL to 1.1.1i.

* Mon May 14 2018 Yichun Zhang (agentzh) 1.1.0h-1
- upgraded openresty-openssl to 1.1.0h.
```

**Comment by spacewander** [comment]
APISIX is changing rapidly. It is cumbersome to maintain a changelog.

**Comment by kwanhur** [comment]
Okay, maybe some efficient solutions will come from APISIX Community.
