### ISSUE TITLE
bug：libldap-2.4.so.2 is missing when using alpine as base image

### ISSUE THREAD

**Issue by soulbird** [api7/apisix-build-tools#176]

**Comment by spacewander** [comment]
The ldap is added in here: https://github.com/apache/apisix-docker/blob/e398cb6ac7f38e646f9033f70ee86fb7a41ef104/alpine/Dockerfile#L51

**Comment by soulbird** [comment]
alreay fixed #278

**Comment by soulbird** [comment]
That apisix-base image don't need this. The libldap already added in https://github.com/apache/apisix-docker/pull/278
