### ISSUE TITLE
Github Action can't pull some goproxy.cn package

### ISSUE THREAD

**Issue by zaunist** [api7/apisix-build-tools#177]
Just look here https://github.com/api7/api7-dashboard/runs/5764328092?check_suite_focus=true#step:5:4512

The environment: https://github.com/api7/apisix-build-tools/blob/50d073305b35397e039ffe9dc9cfba5b6e969bcb/utils/install-common.sh#L154

If we often use it on a foreign machine, such as github action,why we use `goproxy.cn` as the proxy service?

**Comment by starsz** [comment]
Good capture.
> why we use goproxy.cn as the proxy service?

I think the reason is that we may use it in China.

We can use an environment variable to replace it.

**Comment by zaunist** [comment]
> 

Got it.

**Comment by leslie-tsang** [comment]
@zaunist Would you like to submit a PR to fix it ?
