### ISSUE TITLE
help request: get a error when installing apisix by rpm.

### ISSUE THREAD

**Issue by wangfeng22** [api7/apisix-build-tools#258]
I have packaged apisix-*.rpm and apisix-base-*.rpm. I have installed apisix-base, but the following error happened when I  was installing apisix.

<img width="552" alt="企业微信截图_9017d317-d45d-4f84-a7cf-f1c5ad730f39" src="https://user-images.githubusercontent.com/42538040/203025472-288a6eb4-f1e1-4049-9e25-0801374d3e75.png">

**Comment by tzssangglass** [comment]
remove openresty on your env
