### ISSUE TITLE
proposal: A brew package for apisix installation

### ISSUE THREAD

**Issue by zhangw** [api7/apisix-build-tools#262]
Hi team:
It is not a serious issue, just a proposal.
I make a brew package for apisix installation on MacOS. The project here it is: https://github.com/zhangw/homebrew-apisix.
Considering more developers may use MacOS as the development env, the installation base upon brew is a handy way in this case.
Could you help to review this project and give more suggestions?

**Comment by tzssangglass** [comment]
Unfortunately, I don't have the energy to do this.

But we can wait and see if more people need to install APISIX on macOS, and if this demand is huge, then we'll consider doing this together.

**Comment by zhangw** [comment]
Thanks for your reply, I understood your meanings, this discussion should be closed and I will do something for brew package by myself.
