### ISSUE TITLE
package error, faild to clone git repository

### ISSUE THREAD

**Issue by MilkWangStudio** [api7/apisix-build-tools#265]
1. git clone https://github.com/api7/apisix-build-tools
2. make package type=deb app=apisix version=3.0.0 checkout=3.0.0

```
Installing https://luarocks.org/lua-resty-timer-1.1.0-1.src.rock

lua-resty-timer 1.1.0-1 is now installed in /tmp/build/output/apisix/usr/local/apisix/deps (license: Apache 2.0)

lua-resty-dns-client 6.0.2-1 depends on binaryheap >= 0.4 (not installed)
Installing https://luarocks.org/binaryheap-0.4-1.src.rock

binaryheap 0.4-1 depends on lua >= 5.1 (5.1-1 provided by VM)
binaryheap 0.4-1 is now installed in /tmp/build/output/apisix/usr/local/apisix/deps (license: MIT/X11)

lua-resty-dns-client 6.0.2-1 depends on luaxxhash >= 1.0 (not installed)
Installing https://luarocks.org/luaxxhash-1.0.0-1.rockspec
Cloning into 'luaxxhash'...
Note: switching to '7bcca4f6da3385ca43eb2e3378ae7a66762bb4df'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false


luaxxhash 1.0.0-1 is now installed in /tmp/build/output/apisix/usr/local/apisix/deps (license: MIT)

lua-resty-dns-client 6.0.2-1 is now installed in /tmp/build/output/apisix/usr/local/apisix/deps (license: Apache 2.0)

apisix master-0 depends on lua-resty-template 2.0 (not installed)
Installing https://luarocks.org/lua-resty-template-2.0-1.src.rock

lua-resty-template 2.0-1 depends on lua >= 5.1 (5.1-1 provided by VM)
lua-resty-template 2.0-1 is now installed in /tmp/build/output/apisix/usr/local/apisix/deps (license: BSD)

apisix master-0 depends on lua-resty-etcd 1.9.0 (not installed)
Installing https://luarocks.org/lua-resty-etcd-1.9.0-0.src.rock
Missing dependencies for lua-resty-etcd 1.9.0-0:
   api7-lua-resty-http 0.1.0 (not installed)
   luafilesystem 1.7.0-2 (not installed)
   penlight 1.9.2-1 (not installed)
   lua-typeof 0.1 (not installed)

lua-resty-etcd 1.9.0-0 depends on api7-lua-resty-http 0.1.0 (not installed)
Installing https://luarocks.org/api7-lua-resty-http-0.1.0-0.rockspec
Cloning into 'lua-resty-http'...
fatal: unable to access 'https://github.com/api7/lua-resty-http/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

Error: Failed installing dependency: https://luarocks.org/lua-resty-etcd-1.9.0-0.src.rock - Failed installing dependency: https://luarocks.org/api7-lua-resty-http-0.1.0-0.rockspec - Failed cloning git repository.
The command '/bin/sh -c /install-common.sh install_apisix     && /determine-dist.sh' returned a non-zero code: 1
make: *** [Makefile:131: build-apisix-deb] Error 1
```

**Comment by lakewatcher** [comment]
我是这么解决的：把里面的git仓库，导入到公司的gitlab 设为公共可访问，修改源码里面的url。就可以拉下来了。

detached HEAD 是将源码结尾的加了 .git

![image-20221228164611495](https://user-images.githubusercontent.com/27823963/210055718-8348def0-fc3f-483e-845a-93555b86ac8b.png)

示例：
git clone --depth=1 -b v0.5.3 http://xxx/lua-var-nginx-module 
lua-var-nginx-module-v0.5.3
Cloning into 'lua-var-nginx-module-v0.5.3'...
error: RPC failed; result=22, HTTP code = 422
fatal: The remote end hung up unexpectedly

[apps@TLVM202016217 ~]$ git clone --depth=1 -b v0.5.3 http://xxx/lua-var-nginx-module.git  lua-var-nginx-module-v0.5.3
Cloning into 'lua-var-nginx-module-v0.5.3'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 30 (delta 3), reused 21 (delta 2), pack-reused 0
Unpacking objects: 100% (30/30), done.

**Comment by MilkWangStudio** [comment]
> 我是这么解决的：把里面的git仓库，导入到公司的gitlab 设为公共可访问，修改源码里面的url。就可以拉下来了。
> 
> detached HEAD 是将源码结尾的加了 .git
> 
> 示例： git clone --depth=1 -b v0.5.3 http://xxx/lua-var-nginx-module lua-var-nginx-module-v0.5.3 Cloning into 'lua-var-nginx-module-v0.5.3'... error: RPC failed; result=22, HTTP code = 422 fatal: The remote end hung up unexpectedly
> 
> [apps@TLVM202016217 ~]$ git clone --depth=1 -b v0.5.3 http://xxx/lua-var-nginx-module.git lua-var-nginx-module-v0.5.3 Cloning into 'lua-var-nginx-module-v0.5.3'... remote: Enumerating objects: 30, done. remote: Counting objects: 100% (30/30), done. remote: Compressing objects: 100% (26/26), done. remote: Total 30 (delta 3), reused 21 (delta 2), pack-reused 0 Unpacking objects: 100% (30/30), done.

太机智了，感谢！
