### ISSUE TITLE
Please help me  Connection refused  https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh

### ISSUE THREAD

**Issue by woyouyitouchenfeijv** [api7/apisix-build-tools#286]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/27728236/227257173-0d85ddfa-a656-426f-8fce-948c07582aac.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/27728236/227257316-b50721bd-1992-478a-8093-5d8d0577b5ea.png">

I don't think it's a problem with my web😭

**Comment by monkeyDluffy6017** [comment]
It's your network‘s problem. Try to `dig raw.githubusercontent.com`
