### ISSUE TITLE
feat: we need to test the RPM after building

### ISSUE THREAD

**Issue by starsz** [api7/apisix-build-tools#37]
Now, we don't test the rpm after building.
I think we should add an action to test this.

**Comment by EnableAsync** [comment]
I will do this, I plan to do some basic tests like apisix-docker, any advice for me?

**Comment by starsz** [comment]
> I will do this, I plan to do some basic tests like apisix-docker, any advice for me?

That's OK. We can add it first. 😄

**Comment by EnableAsync** [comment]
> > I will do this, I plan to do some basic tests like apisix-docker, any advice for me?
> 
> That's OK. We can add it first. 😄

https://github.com/api7/apisix-build-tools/pull/58
I found a similar pr that has been merged, is there anything else I can do?

**Comment by starsz** [comment]
Oh. I think #58 is OK. We can close this issue now.
