### ISSUE TITLE
Add CI for the apisix-openresty build

### ISSUE THREAD

**Issue by spacewander** [api7/apisix-build-tools#43]
Need to verify if the output rpm can be installed

**Comment by Yiyiyimu** [comment]
could take [apisix centos rpm test](https://github.com/apache/apisix/blob/master/.github/workflows/centos7-ci.yml) as reference if needed

**Comment by tzssangglass** [comment]
> could take [apisix centos rpm test](https://github.com/apache/apisix/blob/master/.github/workflows/centos7-ci.yml) as reference if needed

got, thx. and I have one more question, if runs on ubuntu and execute `make package type=rpm app=apisix-openresty version=1.19.3.2`, it will build rpm, reference to 

https://github.com/api7/apisix-build-tools/blob/20a721f9041f5f7623376a879238aeef3e099aac/Makefile#L81-L86

in Dockerfile.apisix-openresty.rpm

https://github.com/api7/apisix-build-tools/blob/20a721f9041f5f7623376a879238aeef3e099aac/dockerfiles/Dockerfile.apisix-openresty.rpm#L1-L11

which copies the `build-apisix-openresty-centos7.sh`, this means base build rpm in docker based on centos7 image, so I don't need to build centos7 environment in CI with docker?

I'm not sure.

**Comment by spacewander** [comment]
We need to test if the rpm can be installed, so we need CentOS.

**Comment by Yiyiyimu** [comment]
> We need to test if the rpm can be installed, so we need CentOS.

Sry forgot about that. Then we need CI other than Github Actions I guess
