### ISSUE TITLE
Issue while installing the package.

### ISSUE THREAD

**Issue by Kushal-kothari** [api7/apisix-build-tools#59]
I am facing the issue while installing apisix-build-tools.
My host system is Ubuntu (I installed all the dependencies).
![docker_error](https://user-images.githubusercontent.com/58383771/125571602-384f4222-bc78-48c4-af34-dffb27aa5fd9.png)

**Comment by EnableAsync** [comment]
Hi, it looks like the variable `PWD` is not set. What happens when you execute `echo $PWD` ?

**Comment by Kushal-kothari** [comment]
> Hi, it looks like the variable `PWD` is not set. What happens when you execute `echo $PWD` ?
```T
kushal@kushal:~/Desktop/Apache/project/apisix-build-tools$ echo $PWD
/home/kushal/Desktop/Apache/project/apisix-build-tools
```

**Comment by EnableAsync** [comment]
> > Hi, it looks like the variable `PWD` is not set. What happens when you execute `echo $PWD` ?
> 
> ```perl
> kushal@kushal:~/Desktop/Apache/project/apisix-build-tools$ echo $PWD
> /home/kushal/Desktop/Apache/project/apisix-build-tools
> ```

What about `echo ${PWD}` ?

**Comment by Kushal-kothari** [comment]
> What about `echo ${PWD}` ?
```T
kushal@kushal:~/Desktop/Apache/project/apisix-build-tools$ echo ${PWD}
/home/kushal/Desktop/Apache/project/apisix-build-tools
```

**Comment by tzssangglass** [comment]
hi, @EnableAsync any news?

**Comment by EnableAsync** [comment]
> hi, @EnableAsync any news?

Are you in the same situation?

**Comment by Kushal-kothari** [comment]
@tzssangglass @EnableAsync .I am not sure why but, I am able to build the package now by manually installing the fpm dependency first and then running the container again.
```
sudo gem install --no-document fpm
```

**Comment by EnableAsync** [comment]
> @tzssangglass @EnableAsync .I am not sure why but, I am able to build the package now by manually installing the fpm dependency first and then running the container.
> 
> ```
> sudo gem install --no-document fpm
> ```

I guess it's because you retry it.
According to your previous case, it has been packaged successfully, but there is an error when copying RPM from docker container to local, specifically because the value of `$PWD` is not obtained.

**Comment by Kushal-kothari** [comment]
> I guess it's because you retry it.
> According to your previous case, it has been packaged successfully, but there is an error when copying RPM from a docker container to local, specifically because the value of `$PWD` is not obtained.

Yes true!. I am closing this issue as this error of mine is solved. Thanks @EnableAsync
