### ISSUE TITLE
feat: Add distribution information for rpm

### ISSUE THREAD

**Issue by imjoey** [api7/apisix-build-tools#64]
In general, the name of the rpm artifact often contains the distribution of the supported OS. For example, `openresty-1.19.3.2-1.el8.x86_64.rpm` shows that it's for CentOS 8. While the rpm files for apisix do not contain the distribution information and users may get confused to know which OS the `apisix-2.8-0.x86_64.rpm` is for. 

So it would be great if we could make use of the `--rpm-dist` flag of `fpm` to add the distribution of rpm, such as: `apisix-2.8-0.el8.x86_64.rpm`. Furthermore, this improvement may also allow us to make one rpm artifact for each version of one distribution.

BTW: the `1` is often used as the first release version of one rpm. So do we need to change the current `0` to `1`, like: `apisix-2.8-1.el8.x86_64.rpm`?

Any feedback is welcome. Thanks.

**Comment by spacewander** [comment]
LGTM
