### ISSUE TITLE
feat: Make this repository versioned

### ISSUE THREAD

**Issue by imjoey** [api7/apisix-build-tools#75]
The apache/apisix, apache/apisix-dashboard, and some other projects are using this tool for building and packaging. But they seem always rely on the latest code from the master branch, which actully is a non-persistent dependency.

For example, the https://github.com/api7/apisix-build-tools/pull/67 renamed the rpm name, which caused CI failures in both apache/apisix and apache/apisix-dashboard.

So I would propose to make this repository under versioning control, as well as only the versioned code could be the dependency of other projects. I would recommend the first version/tag to be `2.0.0`.

What do you think? @spacewander @tzssangglass

**Comment by spacewander** [comment]
LGTM
